"""update profile picture url column

Revision ID: 19ed035c0802
Revises: cd36f2e97dc5
Create Date: 2026-07-14 12:17:16.421803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19ed035c0802'
down_revision: Union[str, Sequence[str], None] = 'cd36f2e97dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_profile_picture_url_fkey'), 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('users_profile_picture_url_fkey'), 'users', 'documents', ['profile_picture_url'], ['document_url'])
    # ### end Alembic commands ###
