"""remove forein key constraint

Revision ID: adfb4e3e737c
Revises: b71d879c4e3c
Create Date: 2026-07-15 14:26:52.491186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adfb4e3e737c'
down_revision: Union[str, Sequence[str], None] = 'b71d879c4e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'document_type',
               existing_type=postgresql.ENUM('PROFILE_PIC', 'ATTACHMENT', name='documenttype'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'document_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PROFILE_PIC', 'ATTACHMENT', name='documenttype'),
               existing_nullable=False)
    # ### end Alembic commands ###
