"""remove forein key constraint

Revision ID: b71d879c4e3c
Revises: f4cdbda10c87
Create Date: 2026-07-15 13:52:21.014510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b71d879c4e3c'
down_revision: Union[str, Sequence[str], None] = 'f4cdbda10c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('attachments_attachment_url_fkey'), 'attachments', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('attachments_attachment_url_fkey'), 'attachments', 'documents', ['attachment_url'], ['document_url'])
    # ### end Alembic commands ###
