"""create initial migration

Revision ID: cd36f2e97dc5
Revises: 
Create Date: 2026-07-13 16:03:09.267858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.config import settings
from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = 'cd36f2e97dc5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('PROFILE_PIC', 'ATTACHMENT', name='documenttype'), nullable=False),
    sa.Column('document_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_url')

    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'AUTHOR', 'EDITOR', name='role'), nullable=False),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_picture_url'], ['documents.document_url'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('contents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.UUID(), nullable=True),
    sa.Column('author', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('content_status', sa.Enum('DRAFT', 'UNDER_AI_REVIEW', 'UNDER_EDITOR_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'PUBLISHED', name='contentstatus'), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_recommendation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.UUID(), nullable=False),
    sa.Column('suggestions', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.UUID(), nullable=False),
    sa.Column('attachment_url', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_url'], ['documents.document_url'], ),
    sa.ForeignKeyConstraint(['content'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['content'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    connection = op.get_bind()

    connection.execute(
                sa.text(
                """
                    INSERT INTO users (
                        id,
                        email,
                        first_name,
                        last_name,
                        role,
                        profile_picture_url,
                        created_by,
                        created_at,
                        updated_at
                    )
                    values(
                        :id,
                        :email,
                        :first_name,
                        :last_name,
                        :role,
                        :profile_picture_url,
                        :created_by,
                        :created_at,
                        :updated_at
                    )
                """),
                [
                    {
                        'id' : settings.ADMIN_ID,
                        'email' : settings.ADMIN_EMAIL,
                        'first_name' : settings.ADMIN_FIRST_NAME,
                        'last_name' : settings.ADMIN_LAST_NAME,
                        'role' : "ADMIN",
                        'profile_picture_url' : None,
                        'created_by': settings.ADMIN_ID,
                        'created_at': datetime.now(),
                        'updated_at': datetime.now()
                    }
                ]
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drafts')
    op.drop_table('attachments')
    op.drop_table('ai_recommendation')
    op.drop_table('contents')
    op.drop_table('categories')
    op.drop_table('users')
    op.drop_table('documents')
    # ### end Alembic commands ###
