"""add column published at and score

Revision ID: f3df2564bbae
Revises: e390a5f1917a
Create Date: 2026-07-14 18:04:27.038643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3df2564bbae'
down_revision: Union[str, Sequence[str], None] = 'e390a5f1917a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_recommendation', sa.Column('score', sa.Integer(), nullable=False))
    op.add_column('contents', sa.Column('published_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'published_at')
    op.drop_column('ai_recommendation', 'score')
    # ### end Alembic commands ###
