"""update content_status type to string

Revision ID: f4cdbda10c87
Revises: f3df2564bbae
Create Date: 2026-07-15 13:28:38.402128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4cdbda10c87'
down_revision: Union[str, Sequence[str], None] = 'f3df2564bbae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contents', 'content_status',
               existing_type=postgresql.ENUM('DRAFT', 'UNDER_AI_REVIEW', 'UNDER_EDITOR_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'PUBLISHED', name='contentstatus'),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contents', 'content_status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('DRAFT', 'UNDER_AI_REVIEW', 'UNDER_EDITOR_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'PUBLISHED', name='contentstatus'),
               existing_nullable=True)
    # ### end Alembic commands ###
