spring.application.name=${APPLICATION_NAME}

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}

custom.jwt.secret=${JWT_SECRET_KEY}
custom.jwt.expiration=${JWT_EXPIRATION_TIME}

server.tomcat.connection-timeout=${CONNECTION_TIMEOUT}

spring.datasource.driver-class-name=${HIBERNATE_DRIVER_CLASS}
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT}

cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
cloud.aws.region.static=${AWS_REGION}

aws.bucket.name=${AWS_BUCKET_NAME}